"""Initial tables again

Revision ID: 4da5183dc371
Revises: 86849ca32f7b
Create Date: 2026-01-22 14:05:46.042046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4da5183dc371'
down_revision: Union[str, Sequence[str], None] = '86849ca32f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to be idempotent ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'venues' not in existing_tables:
        op.create_table('venues',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('address', sa.String(length=500), nullable=False),
            sa.Column('latitude', sa.Float(), nullable=False),
            sa.Column('longitude', sa.Float(), nullable=False),
            sa.Column('phone', sa.String(length=20), nullable=True),
            sa.Column('website', sa.String(length=500), nullable=True),
            sa.Column('neighborhood', sa.String(length=100), nullable=True),
            sa.Column('venue_type', sa.String(length=50), nullable=True),
            sa.Column('verified', sa.Boolean(), nullable=True),
            sa.Column('active', sa.Boolean(), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )

    # create indexes if missing
    if 'venues' in existing_tables:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('venues')]
        if 'ix_venues_name' not in existing_indexes:
            op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
        if 'ix_venues_neighborhood' not in existing_indexes:
            op.create_index(op.f('ix_venues_neighborhood'), 'venues', ['neighborhood'], unique=False)

    if 'deals' not in existing_tables:
        op.create_table('deals',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('venue_id', sa.UUID(), nullable=False),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('category', sa.String(length=50), nullable=True),
            sa.Column('deal_type', sa.String(length=50), nullable=True),
            sa.Column('original_price', sa.Float(), nullable=True),
            sa.Column('deal_price', sa.Float(), nullable=True),
            sa.Column('discount_percentage', sa.Float(), nullable=True),
            sa.Column('items', sa.ARRAY(sa.String()), nullable=True),
            sa.Column('active', sa.Boolean(), nullable=True),
            sa.Column('verified', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    if 'happy_hour_schedules' not in existing_tables:
        op.create_table('happy_hour_schedules',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('venue_id', sa.UUID(), nullable=False),
            sa.Column('day_of_week', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.Time(), nullable=False),
            sa.Column('end_time', sa.Time(), nullable=False),
            sa.Column('deal_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('restrictions', sa.Text(), nullable=True),
            sa.Column('active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostGIS internal tables should not be recreated by migrations.
    op.drop_table('happy_hour_schedules')
    op.drop_table('deals')
    op.drop_index(op.f('ix_venues_neighborhood'), table_name='venues')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
