"""Initial tables: venues, deals, happy_hour_schedules

Revision ID: 86849ca32f7b
Revises: 11cfbfc180c0
Create Date: 2026-01-22 13:54:44.324322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86849ca32f7b'
down_revision: Union[str, Sequence[str], None] = '11cfbfc180c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed PostGIS internal table operations (spatial_ref_sys) because
    # the PostGIS extension manages these objects and they must not be
    # dropped or created by migrations.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostGIS internal tables should not be recreated by migrations.
    pass